version: "3.3"
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes:
      - ./data/:/var/lib/pgadmin/
    restart: always
    networks:
      - webgis
    environment:
      - PGADMIN_DEFAULT_EMAIL=change_email@mail.some
      - PGADMIN_DEFAULT_PASSWORD=change_password
volumes:
  data:
networks:
  webgis:
    external: true